apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diploma-app
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.diploma.local  # Замени на свой домен
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diploma-app
            port:
              number: 80
