apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diploma-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  rules:
  - host: diploma.89.169.142.18.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diploma-app
            port:
              number: 80
  tls:
  - hosts:
    - diploma.89.169.142.18.nip.io
    secretName: diploma-app-tls
