apiVersion: v1
kind: Service
metadata:
  name: diploma-app
  namespace: default
  labels:
    app: diploma-app
spec:
  selector:
    app: diploma-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics
  type: ClusterIP
